import { useEffect, useState } from 'react'
import { Card } from '../components/Card'
import { FeedbackState } from '../components/FeedbackState'
import { PageTitle } from '../components/PageTitle'
import { RewardComparisonChart } from '../features/comparison/RewardComparisonChart'
import { KpiGrid } from '../features/dashboard/KpiGrid'
import { fetchOverview } from '../services/resultsService'
import type { OverviewResponse } from '../types/results'
import { toFixed, toPercent, titleCase } from '../utils/format'

export function OverviewPage() {
  const [data, setData] = useState<OverviewResponse | null>(null)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    fetchOverview()
      .then(setData)
      .catch((err: Error) => setError(err.message))
  }, [])

  return (
    <div className="space-y-6">
      <PageTitle
        eyebrow="Product Pitch"
        title="Budgeted Interactive Movie Recommender"
        description="A reinforcement-learning assistant that intelligently decides when to ask preference questions and when to recommend a movie genre, maximizing acceptance while controlling user fatigue."
      />

      <Card className="bg-gradient-to-r from-emerald-900/50 via-cyan-900/40 to-slate-900">
        <h3 className="text-xl font-semibold text-white">Why this matters</h3>
        <p className="mt-3 max-w-3xl text-slate-200">
          Most recommenders either guess too early or overwhelm users with too many questions. Our budget-aware policy
          adapts to each user profile in real time and preserves engagement by balancing information gain with friction.
        </p>
      </Card>

      {error ? <FeedbackState title="Unable to load overview metrics" message={error} /> : null}

      <KpiGrid
        bestReward={toFixed(data?.kpis.best_reward, 2)}
        topPolicy={data?.kpis.best_performing_algorithm ? titleCase(data.kpis.best_performing_algorithm) : 'N/A'}
        bestAcceptanceRate={toPercent(data?.kpis.best_acceptance_rate)}
        avgQuestionsAsked={toFixed(data?.kpis.avg_questions_asked, 2)}
        bestAlgorithm={data?.kpis.best_performing_algorithm ? titleCase(data.kpis.best_performing_algorithm) : 'N/A'}
      />

      <Card>
        <h3 className="text-lg font-semibold text-white">Current algorithm snapshot</h3>
        <p className="mt-2 text-sm text-slate-400">
          The chart below is loaded from the latest comparison artifact generated by the existing backend evaluation
          pipeline.
        </p>
        {data?.metrics?.length ? (
          <div className="mt-5">
            <RewardComparisonChart metrics={data.metrics} />
          </div>
        ) : (
          <div className="mt-5">
            <FeedbackState
              title="No comparison results found yet"
              message="Run the backend evaluation and comparison scripts to populate summary artifacts under results/comparisons."
            />
          </div>
        )}
      </Card>
    </div>
  )
}
